/* ============================================================================
   Guides: landing page renderer.
   Loaded as a deferred <script> from index.html.

   The page is a catalogue: a plain statement of what the site is, a key to the
   three formats, the three most recently updated items, a format filter plus
   search, and then one section per subject listing every item with its format,
   length and date. Each topic appears once; there is no featured card.
   ============================================================================ */

(function () {
    "use strict";

    // ------------------------------------------------------------------------
    // 1. Registry
    //
    //    Categories are subjects. Format (deep dive, guide, cheat sheet) is a
    //    label and a filter, never a category. `accent` is kept because
    //    scripts/check-site.mjs reads the category names through it.
    //
    //    Card fields:
    //      type        'guide' | 'tutorial'. Routing only. 'guide' links to
    //                  guides/<file>.html, 'tutorial' to tutorial.html?slug=.
    //      format      'deep-dive' | 'guide' | 'reference'. Presentation and
    //                  the format filter. Kept separate from `type`.
    //      minutes     generated by scripts/generate.mjs from word counts.
    //      lessons     multi-lesson tutorials only.
    //      updated     editorial date, YYYY-MM-DD; drives "Recently updated".
    //      tags        searchable, never rendered.
    // ------------------------------------------------------------------------

    const CATEGORIES = [
        {
            name: 'AI engineering',
            accent: 'blue',
            blurb: 'Agent frameworks, graph databases and the tools used to build AI applications.',
        },
        {
            name: 'Finance and economics',
            accent: 'blue',
            blurb: 'How markets and economies work: bonds, commodities, company valuation and the economy of Japan.',
        },
    ];

    const CARDS = [
        // ---- AI engineering -------------------------------------------------
        {
            type: 'tutorial', format: 'deep-dive', category: 'AI engineering',
            title: 'Neo4j & GraphRAG', href: 'tutorial.html?slug=neo4j',
            tags: ['Cypher', 'GraphRAG', 'Python', 'Neo4j', 'Graph databases'],
            description: 'Graph databases with Neo4j: data modelling, the Cypher query language, GraphRAG, and using a graph as memory for AI agents, ending with a worked banking project.',
            updated: '2026-06-04', lessons: 12, minutes: 159,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'Google ADK', href: 'guides/googleadk.html',
            tags: ['Python', 'Gemini', 'Vertex AI', 'Agent SDK'],
            description: "Google's Agent Development Kit: building agents in code, workflow agents, callbacks, and deployment to Vertex AI.",
            updated: '2026-06-02', minutes: 14,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'Semantic Kernel', href: 'guides/semantickernel.html',
            tags: ['Python', 'C#', 'Java', 'Enterprise SDK', 'Microsoft'],
            description: "Microsoft's SDK for connecting large language models to existing code through plugins, planners and memory.",
            updated: '2026-01-18', minutes: 9,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'LangGraph', href: 'guides/langgraph.html',
            tags: ['Python', 'JS/TS', 'Stateful graph', 'Human in the loop'],
            description: 'Building stateful agents as graphs, with loops, persistence and human-in-the-loop steps.',
            updated: '2025-12-21', minutes: 9,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'PydanticAI', href: 'guides/pydanticai.html',
            tags: ['Python', 'Type-safe', 'Validation'],
            description: 'Building type-safe agents in Python, with Pydantic models validating inputs and outputs.',
            updated: '2025-12-20', minutes: 6,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'CrewAI', href: 'guides/crewai.html',
            tags: ['Python', 'Crew pattern', 'Role-playing agents'],
            description: 'Multi-agent systems built from role-based agents that work through a defined process.',
            updated: '2025-12-03', minutes: 4,
        },

        // ---- Finance and economics -------------------------------------------
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: "Japan's Economy", href: 'tutorial.html?slug=japan-economy',
            tags: ['Finance', 'Macro', 'Japan', 'Bank of Japan', 'Yen', 'JGBs', 'Monetary policy', 'Deflation', 'Carry trade'],
            description: "Japan's economy from the 1985 Plaza Accord to 2026: deflation, zero and negative interest rates, quantitative easing, yield curve control, the yen, government debt, and why Japanese interest rates affect markets elsewhere.",
            updated: '2026-10-05', lessons: 12, minutes: 106,
        },
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: 'Commodity Markets', href: 'tutorial.html?slug=commodity-markets',
            tags: ['Finance', 'Macro', 'Commodities', 'Futures', 'Oil', 'Gold', 'Hedging', 'Forward curve'],
            description: 'How oil, metals, grain and gas are traded and priced: physical and futures markets, hedging, the forward curve, the main price drivers, and major market shocks from 1973 to 2026.',
            updated: '2026-10-05', lessons: 14, minutes: 149,
        },
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: 'Global Bond Markets', href: 'tutorial.html?slug=global-bond-markets',
            tags: ['Finance', 'Macro', 'Fixed income', 'Yield curve', 'Duration'],
            description: 'How bond markets work: prices and yields, duration, the yield curve, the main participants and bond funds, with the US, UK and Indian markets compared and eight historical episodes.',
            updated: '2026-09-27', lessons: 9, minutes: 86,
        },
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: 'Investment Valuation',
            href: 'tutorial.html?slug=investment-valuation&lesson=valuation-from-zero-a-complete-guide',
            tags: ['Finance', 'DCF', 'Accounting', 'Multiples'],
            description: 'Valuing a business from first principles: accounting basics, discounted cash flow and valuation multiples, worked through one example company.',
            updated: '2026-06-15', lessons: 1, minutes: 48,
        },

        // ---- AI engineering: cheat sheets -------------------------------------
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'AutoGen', href: 'guides/autogen.html',
            tags: ['Python', '.NET', 'Multi-agent chat', 'Microsoft'],
            description: 'Multi-agent conversation patterns and group-chat orchestration in Microsoft AutoGen.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Haystack', href: 'guides/haystack.html',
            tags: ['Python', 'RAG', 'Pipelines', 'Search'],
            description: 'Pipelines for retrieval-augmented generation and search with Haystack.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'LlamaIndex', href: 'guides/llamaindex.html',
            tags: ['Python', 'TS', 'Data framework', 'RAG'],
            description: 'Ingesting, indexing and querying your own documents with LlamaIndex.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Phidata', href: 'guides/phidata.html',
            tags: ['Python', 'Memory', 'Tools'],
            description: 'Agents with persistent memory and database-backed state in Phidata.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Smolagents', href: 'guides/smolagents.html',
            tags: ['Python', 'Hugging Face', 'Code agents'],
            description: "Hugging Face's small agent library, in which the agent writes and runs Python code.",
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Swarm', href: 'guides/swarm.html',
            tags: ['Python', 'OpenAI', 'Handoff pattern'],
            description: "OpenAI's experimental library for lightweight hand-offs between agents.",
            updated: '2025-12-03', minutes: 1,
        },
    ];

    // ------------------------------------------------------------------------
    // 2. Helpers
    // ------------------------------------------------------------------------

    const FORMATS = [
        { key: 'deep-dive', label: 'Deep dive', plural: 'Deep dives', note: 'a full course on one subject, usually in several lessons' },
        { key: 'guide', label: 'Guide', plural: 'Guides', note: 'a single page on one framework' },
        { key: 'reference', label: 'Cheat sheet', plural: 'Cheat sheets', note: 'a one-page summary' },
    ];
    const FORMAT_LABEL = Object.fromEntries(FORMATS.map(f => [f.key, f.label]));
    const FORMAT_ORDER = Object.fromEntries(FORMATS.map((f, i) => [f.key, i]));
    const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

    function escapeHtml(s) {
        return String(s)
            .replace(/&/g, '&amp;').replace(/</g, '&lt;')
            .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }

    function slugifyCategory(name) {
        return 'cat-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    }

    // '2026-10-05' -> '5 Oct 2026' (long) or 'Oct 2026' (short).
    function formatDate(d, long) {
        const [y, m, day] = d.split('-').map(Number);
        return long ? `${day} ${MONTHS[m - 1]} ${y}` : `${MONTHS[m - 1]} ${y}`;
    }

    function readingTime(min) {
        if (!min) return null;
        if (min < 60) return `${min} min`;
        const h = Math.floor(min / 60);
        const m = min % 60;
        return m ? `${h} hr ${m} min` : `${h} hr`;
    }

    function searchHay(card) {
        return [
            card.title, card.description, FORMAT_LABEL[card.format],
            ...(card.tags || []), card.category,
        ].join(' ').toLowerCase();
    }

    // Newest first; on a tie, the card listed first in CARDS wins, so the
    // order never depends on how the browser's sort treats equal dates.
    function byRecency(list) {
        return list
            .map(c => [c, CARDS.indexOf(c)])
            .sort(([a, i], [b, j]) => (a.updated === b.updated ? i - j : a.updated < b.updated ? 1 : -1))
            .map(([c]) => c);
    }

    function cardsIn(cat) {
        return CARDS.filter(c => c.category === cat.name);
    }

    function presentCategories() {
        return CATEGORIES.map(cat => ({ cat, items: cardsIn(cat) })).filter(x => x.items.length);
    }

    const SEP = '<span class="text-gray-300 dark:text-gray-600" aria-hidden="true"> · </span>';

    // ------------------------------------------------------------------------
    // 3. Entry markup
    //
    //    `.hub-card`, `data-search`, `data-category` and `data-format` are the
    //    hooks the filter keys off, so every entry carries them, including the
    //    compact cheat-sheet links.
    // ------------------------------------------------------------------------

    function hooks(card) {
        return `data-search="${escapeHtml(searchHay(card))}" data-category="${escapeHtml(card.category)}" data-format="${card.format}"`;
    }

    function rowHtml(card) {
        const meta = [FORMAT_LABEL[card.format]];
        if (card.lessons && card.lessons > 1) meta.push(`${card.lessons} lessons`);
        const t = readingTime(card.minutes);
        if (t) meta.push(t);
        return `
            <li class="hub-card border-t border-gray-200 dark:border-gray-800" ${hooks(card)}>
                <a href="${escapeHtml(card.href)}" class="group block py-4 sm:grid sm:grid-cols-[1fr_15rem] sm:gap-8">
                    <span class="block">
                        <span class="block text-base sm:text-lg font-semibold text-gray-900 dark:text-gray-100 group-hover:text-blue-700 dark:group-hover:text-blue-400 group-hover:underline underline-offset-2">${escapeHtml(card.title)}</span>
                        <span class="block mt-1 text-[15px] text-gray-600 dark:text-gray-400 leading-relaxed">${escapeHtml(card.description)}</span>
                    </span>
                    <span class="block mt-2 sm:mt-1 sm:text-right text-sm text-gray-500 dark:text-gray-400 tabular">
                        <span class="block">${meta.map(escapeHtml).join(' · ')}</span>
                        <span class="block">Updated ${formatDate(card.updated)}</span>
                    </span>
                </a>
            </li>`;
    }

    // Cheat sheets are one page each, so they share a single line rather than
    // taking a full row apiece.
    function sheetsHtml(cards) {
        if (!cards.length) return '';
        // Each separator sits in the same no-wrap span as the link before it,
        // so a line never starts with a dot.
        const links = cards.map((c, i) => `<span class="whitespace-nowrap"><a href="${escapeHtml(c.href)}" class="hub-card text-gray-900 dark:text-gray-100 hover:text-blue-700 dark:hover:text-blue-400 underline decoration-gray-300 dark:decoration-gray-600 underline-offset-2 hover:decoration-current" ${hooks(c)}>${escapeHtml(c.title)}</a>${i < cards.length - 1 ? '<span class="hub-sep text-gray-300 dark:text-gray-600" aria-hidden="true"> · </span>' : ''}</span>`);
        return `
            <li class="hub-sheets border-t border-gray-200 dark:border-gray-800 py-4 text-[15px] leading-loose">
                <span class="text-gray-600 dark:text-gray-400">Cheat sheets, one page each:</span>
                ${links.join(' ')}
            </li>`;
    }

    function sectionHtml(cat, cards) {
        if (!cards.length) return '';
        const id = slugifyCategory(cat.name);
        const sorted = byRecency(cards).sort((a, b) => FORMAT_ORDER[a.format] - FORMAT_ORDER[b.format]);
        const full = sorted.filter(c => c.format !== 'reference');
        const sheets = sorted.filter(c => c.format === 'reference').sort((a, b) => a.title.localeCompare(b.title));
        return `
            <section id="${id}" class="hub-section mb-12" data-category="${escapeHtml(cat.name)}" aria-labelledby="${id}-h">
                <div class="flex items-baseline gap-3">
                    <h2 id="${id}-h" class="text-xl sm:text-2xl font-semibold text-gray-900 dark:text-gray-100">${escapeHtml(cat.name)}</h2>
                    <span class="text-sm text-gray-500 dark:text-gray-400 tabular hub-section-count">${cards.length}</span>
                </div>
                <p class="mt-1 mb-3 text-[15px] text-gray-600 dark:text-gray-400">${escapeHtml(cat.blurb)}</p>
                <ul class="border-b border-gray-200 dark:border-gray-800">${full.map(rowHtml).join('')}${sheetsHtml(sheets)}</ul>
            </section>`;
    }

    // ------------------------------------------------------------------------
    // 4. Page furniture
    // ------------------------------------------------------------------------

    function renderStats() {
        const slot = document.getElementById('library-stats');
        if (!slot) return;
        const mins = CARDS.reduce((n, c) => n + (c.minutes || 0), 0);
        const dives = CARDS.filter(c => c.format === 'deep-dive').length;
        slot.innerHTML = [
            `${CARDS.length} guides`,
            `${dives} deep dives`,
            `about ${Math.round(mins / 60)} hours of reading`,
        ].join(SEP);
    }

    function renderFormatKey() {
        const slot = document.getElementById('format-key');
        if (!slot) return;
        slot.innerHTML = FORMATS.map(f =>
            `<span class="inline-block mr-5"><span class="font-medium text-gray-700 dark:text-gray-300">${f.label}:</span> ${f.note}</span>`
        ).join('');
    }

    function renderRecent() {
        const slot = document.getElementById('recent');
        if (!slot) return;
        const items = byRecency(CARDS.filter(c => c.updated)).slice(0, 3);
        slot.innerHTML = `
            <h2 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Recently updated</h2>
            <ul class="mt-2 space-y-1.5">${items.map(c => `
                <li class="text-[15px]">
                    <a href="${escapeHtml(c.href)}" class="font-medium text-blue-700 dark:text-blue-400 hover:underline underline-offset-2">${escapeHtml(c.title)}</a>
                    <span class="text-gray-500 dark:text-gray-400">${SEP}${FORMAT_LABEL[c.format]}${SEP}<span class="tabular">${formatDate(c.updated, true)}</span></span>
                </li>`).join('')}
            </ul>`;
    }

    function renderMastheadTopics() {
        const slot = document.getElementById('masthead-topics');
        if (!slot) return;
        slot.innerHTML = presentCategories().map(({ cat }) => `
            <a href="#${slugifyCategory(cat.name)}"
               class="inline-flex items-center py-3 lg:py-0 text-gray-600 dark:text-gray-300 hover:text-blue-700 dark:hover:text-blue-400 transition-colors whitespace-nowrap">${escapeHtml(cat.name)}</a>
        `).join('');
    }

    function renderFormatButtons() {
        const slot = document.getElementById('format-buttons');
        if (!slot) return;
        const opts = [{ key: 'all', plural: 'All' }, ...FORMATS];
        slot.innerHTML = opts.map(f => {
            const n = f.key === 'all' ? CARDS.length : CARDS.filter(c => c.format === f.key).length;
            return `<button type="button" data-format-filter="${f.key}" aria-pressed="${f.key === 'all'}"
                class="fmt-btn px-3 py-2.5 lg:py-1.5 text-sm rounded-md border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:border-gray-500 dark:hover:border-gray-400">${f.plural} <span class="tabular text-gray-500 dark:text-gray-400">${n}</span></button>`;
        }).join('');
    }

    function renderIndex() {
        const root = document.getElementById('hub');
        if (!root) return;
        root.innerHTML = CATEGORIES.map(cat => sectionHtml(cat, cardsIn(cat))).join('');
    }

    // ------------------------------------------------------------------------
    // 5. Filter: format buttons and text search combine
    // ------------------------------------------------------------------------

    function setupFilter() {
        const input = document.getElementById('card-filter');
        const empty = document.getElementById('filter-empty');
        const status = document.getElementById('filter-status');
        const buttons = document.querySelectorAll('[data-format-filter]');
        let format = 'all';

        function apply() {
            const q = input ? input.value.toLowerCase().trim() : '';
            let visibleTotal = 0;
            document.querySelectorAll('.hub-section').forEach(section => {
                let visibleInSection = 0;
                section.querySelectorAll('.hub-card').forEach(card => {
                    const match = (!q || card.dataset.search.includes(q)) && (format === 'all' || card.dataset.format === format);
                    card.hidden = !match;
                    if (match) { visibleInSection++; visibleTotal++; }
                });
                // The cheat-sheet line hides when none of its links match, and
                // its separators follow the links that remain.
                section.querySelectorAll('.hub-sheets').forEach(line => {
                    const links = [...line.querySelectorAll('.hub-card')];
                    const shown = links.filter(a => !a.hidden);
                    line.hidden = shown.length === 0;
                    line.querySelectorAll('.hub-sep').forEach((sep, i) => {
                        sep.hidden = links[i].hidden || links.slice(i + 1).every(a => a.hidden);
                    });
                });
                const counter = section.querySelector('.hub-section-count');
                const total = section.querySelectorAll('.hub-card').length;
                if (counter) counter.textContent = (q || format !== 'all') ? `${visibleInSection} of ${total}` : total;
                section.hidden = visibleInSection === 0;
            });
            const filtering = q || format !== 'all';
            if (status) status.textContent = filtering ? `Showing ${visibleTotal} of ${CARDS.length}` : '';
            if (empty) empty.hidden = visibleTotal > 0;
        }

        buttons.forEach(btn => btn.addEventListener('click', () => {
            format = btn.dataset.formatFilter;
            buttons.forEach(b => b.setAttribute('aria-pressed', String(b === btn)));
            apply();
        }));
        if (input) {
            input.addEventListener('input', apply);
            input.addEventListener('keydown', e => {
                if (e.key === 'Escape') { input.value = ''; apply(); }
            });
        }
        apply();
    }

    // ------------------------------------------------------------------------
    // 6. Bootstrap
    // ------------------------------------------------------------------------

    function init() {
        renderStats();
        renderFormatKey();
        renderRecent();
        renderMastheadTopics();
        renderFormatButtons();
        renderIndex();
        setupFilter();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
