/* ============================================================================
   Guides: landing page renderer.
   Loaded as a deferred <script> from index.html.

   The page is a catalogue: a plain statement of what the site is, a key to the
   three formats, the three most recently updated items, a format filter plus
   search, and then one section per subject listing every item with its format,
   length and date. Each topic appears once; there is no featured card.
   ============================================================================ */

(function () {
    "use strict";

    // ------------------------------------------------------------------------
    // 1. Registry
    //
    //    Categories are subjects. Format (deep dive, guide, cheat sheet) is a
    //    label and a filter, never a category. `accent` is kept because
    //    scripts/check-site.mjs reads the category names through it.
    //
    //    Card fields:
    //      type        'guide' | 'tutorial'. Routing only. 'guide' links to
    //                  guides/<file>.html, 'tutorial' to tutorial.html?slug=.
    //      format      'deep-dive' | 'guide' | 'reference'. Presentation and
    //                  the format filter. Kept separate from `type`.
    //      minutes     generated by scripts/generate.mjs from word counts.
    //      lessons     multi-lesson tutorials only.
    //      updated     editorial date, YYYY-MM-DD; drives "Recently updated".
    //      tags        searchable, never rendered.
    //      status      optional factual note shown with the entry, for a tool
    //                  that has been renamed, replaced or retired.
    // ------------------------------------------------------------------------

    const CATEGORIES = [
        {
            name: 'AI engineering',
            accent: 'blue',
            blurb: 'Agent frameworks, graph databases and the tools used to build AI applications.',
        },
        {
            name: 'Finance and economics',
            accent: 'blue',
            blurb: 'How markets and economies work: bonds, commodities, company valuation and the economy of Japan.',
        },
    ];

    const CARDS = [
        // ---- AI engineering -------------------------------------------------
        {
            type: 'tutorial', format: 'deep-dive', category: 'AI engineering',
            title: 'Neo4j & GraphRAG', href: 'tutorial.html?slug=neo4j',
            tags: ['Cypher', 'GraphRAG', 'Python', 'Neo4j', 'Graph databases'],
            description: 'Graph databases with Neo4j: data modelling, the Cypher query language, GraphRAG, and using a graph as memory for AI agents, ending with a worked banking project.',
            updated: '2026-06-04', lessons: 12, minutes: 159,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'Google ADK', href: 'guides/googleadk.html',
            tags: ['Python', 'Gemini', 'Vertex AI', 'Agent SDK'],
            description: "Google's Agent Development Kit: building agents in code, workflow agents, callbacks, and deployment to Vertex AI.",
            updated: '2026-06-02', minutes: 14,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'Semantic Kernel', href: 'guides/semantickernel.html',
            tags: ['Python', 'C#', 'Java', 'Enterprise SDK', 'Microsoft'],
            description: "Microsoft's SDK for connecting large language models to existing code through plugins, planners and memory.",
            status: 'Microsoft now recommends Microsoft Agent Framework, its successor to Semantic Kernel and AutoGen (version 1.0, April 2026), for new projects.',
            updated: '2026-01-18', minutes: 9,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'LangGraph', href: 'guides/langgraph.html',
            tags: ['Python', 'JS/TS', 'Stateful graph', 'Human in the loop'],
            description: 'Building stateful agents as graphs, with loops, persistence and human-in-the-loop steps.',
            updated: '2025-12-21', minutes: 9,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'PydanticAI', href: 'guides/pydanticai.html',
            tags: ['Python', 'Type-safe', 'Validation'],
            description: 'Building type-safe agents in Python, with Pydantic models validating inputs and outputs.',
            updated: '2025-12-20', minutes: 6,
        },
        {
            type: 'guide', format: 'guide', category: 'AI engineering',
            title: 'CrewAI', href: 'guides/crewai.html',
            tags: ['Python', 'Crew pattern', 'Role-playing agents'],
            description: 'Multi-agent systems built from role-based agents that work through a defined process.',
            updated: '2025-12-03', minutes: 4,
        },

        // ---- Finance and economics -------------------------------------------
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: "Japan's Economy", href: 'tutorial.html?slug=japan-economy',
            tags: ['Finance', 'Macro', 'Japan', 'Bank of Japan', 'Yen', 'JGBs', 'Monetary policy', 'Deflation', 'Carry trade'],
            description: "Japan's economy from the 1985 Plaza Accord to 2026: deflation, zero and negative interest rates, quantitative easing, yield curve control, the yen, government debt, and why Japanese interest rates affect markets elsewhere.",
            updated: '2026-10-05', lessons: 12, minutes: 106,
        },
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: 'Commodity Markets', href: 'tutorial.html?slug=commodity-markets',
            tags: ['Finance', 'Macro', 'Commodities', 'Futures', 'Oil', 'Gold', 'Hedging', 'Forward curve'],
            description: 'How oil, metals, grain and gas are traded and priced: physical and futures markets, hedging, the forward curve, the main price drivers, and major market shocks from 1973 to 2026.',
            updated: '2026-10-05', lessons: 14, minutes: 149,
        },
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: 'Global Bond Markets', href: 'tutorial.html?slug=global-bond-markets',
            tags: ['Finance', 'Macro', 'Fixed income', 'Yield curve', 'Duration'],
            description: 'How bond markets work: prices and yields, duration, the yield curve, the main participants and bond funds, with the US, UK and Indian markets compared and eight historical episodes.',
            updated: '2026-09-27', lessons: 9, minutes: 86,
        },
        {
            type: 'tutorial', format: 'deep-dive', category: 'Finance and economics',
            title: 'Investment Valuation',
            href: 'tutorial.html?slug=investment-valuation&lesson=valuation-from-zero-a-complete-guide',
            tags: ['Finance', 'DCF', 'Accounting', 'Multiples'],
            description: 'Valuing a business from first principles: accounting basics, discounted cash flow and valuation multiples, worked through one example company.',
            updated: '2026-06-15', lessons: 1, minutes: 48,
        },

        // ---- AI engineering: cheat sheets -------------------------------------
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'AutoGen', href: 'guides/autogen.html',
            tags: ['Python', '.NET', 'Multi-agent chat', 'Microsoft'],
            description: 'Multi-agent conversation patterns and group-chat orchestration in Microsoft AutoGen.',
            status: 'In maintenance mode since October 2025; succeeded by Microsoft Agent Framework.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Haystack', href: 'guides/haystack.html',
            tags: ['Python', 'RAG', 'Pipelines', 'Search'],
            description: 'Pipelines for retrieval-augmented generation and search with Haystack.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'LlamaIndex', href: 'guides/llamaindex.html',
            tags: ['Python', 'TS', 'Data framework', 'RAG'],
            description: 'Ingesting, indexing and querying your own documents with LlamaIndex.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Phidata', href: 'guides/phidata.html',
            tags: ['Python', 'Memory', 'Tools'],
            description: 'Agents with persistent memory and database-backed state in Phidata.',
            status: 'Renamed Agno in January 2025; this sheet uses the earlier Phidata names.',
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Smolagents', href: 'guides/smolagents.html',
            tags: ['Python', 'Hugging Face', 'Code agents'],
            description: "Hugging Face's small agent library, in which the agent writes and runs Python code.",
            updated: '2025-12-03', minutes: 1,
        },
        {
            type: 'guide', format: 'reference', category: 'AI engineering',
            title: 'Swarm', href: 'guides/swarm.html',
            tags: ['Python', 'OpenAI', 'Handoff pattern'],
            description: "OpenAI's experimental library for lightweight hand-offs between agents.",
            status: 'Replaced by the OpenAI Agents SDK in March 2025; Swarm remains an educational example.',
            updated: '2025-12-03', minutes: 1,
        },
    ];


    // ------------------------------------------------------------------------
    // 2. Helpers
    // ------------------------------------------------------------------------

    const FORMATS = [
        { key: 'deep-dive', label: 'Deep dive', plural: 'Deep dives', note: 'a full course on one subject, usually in several lessons' },
        { key: 'guide', label: 'Guide', plural: 'Guides', note: 'a single page on one framework' },
        { key: 'reference', label: 'Cheat sheet', plural: 'Cheat sheets', note: 'a one-page summary' },
    ];
    const FORMAT_LABEL = Object.fromEntries(FORMATS.map(f => [f.key, f.label]));
    const FORMAT_ORDER = Object.fromEntries(FORMATS.map((f, i) => [f.key, i]));
    const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const SEP = '<span class="sep" aria-hidden="true"> · </span>';

    function escapeHtml(s) {
        return String(s)
            .replace(/&/g, '&amp;').replace(/</g, '&lt;')
            .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    }

    function slugifyCategory(name) {
        return 'cat-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    }

    // '2026-10-05' -> '5 Oct 2026' (long) or 'Oct 2026' (short).
    function formatDate(d, long) {
        const [y, m, day] = d.split('-').map(Number);
        return long ? `${day} ${MONTHS[m - 1]} ${y}` : `${MONTHS[m - 1]} ${y}`;
    }

    function readingTime(min) {
        if (!min) return null;
        if (min < 60) return `${min} min`;
        const h = Math.floor(min / 60);
        const m = min % 60;
        return m ? `${h} hr ${m} min` : `${h} hr`;
    }

    function searchHay(card) {
        return [card.title, card.description, card.status || '', FORMAT_LABEL[card.format],
            ...(card.tags || []), card.category].join(' ').toLowerCase();
    }

    // Newest first; on a tie, the card listed first in CARDS wins, so the
    // order never depends on how a sort treats equal dates.
    function byRecency(list) {
        return list
            .map(c => [c, CARDS.indexOf(c)])
            .sort(([a, i], [b, j]) => (a.updated === b.updated ? i - j : a.updated < b.updated ? 1 : -1))
            .map(([c]) => c);
    }

    const cardsIn = cat => CARDS.filter(c => c.category === cat.name);

    // ------------------------------------------------------------------------
    // 3. Markup
    //
    //    `.hub-card` with `data-search` and `data-format` are the filter's
    //    hooks, so every entry carries them, cheat-sheet links included.
    //    Classes are styled by landing.css.
    // ------------------------------------------------------------------------

    const hooks = card =>
        `data-search="${escapeHtml(searchHay(card))}" data-format="${card.format}"`;

    function rowHtml(card) {
        const meta = [FORMAT_LABEL[card.format]];
        if (card.lessons && card.lessons > 1) meta.push(`${card.lessons} lessons`);
        const t = readingTime(card.minutes);
        if (t) meta.push(t);
        const status = card.status
            ? `<span class="entry-status"><b>Note:</b> ${escapeHtml(card.status)}</span>` : '';
        return `
<li class="entry hub-card" ${hooks(card)}><a href="${escapeHtml(card.href)}">
<span><span class="entry-title">${escapeHtml(card.title)}</span><span class="entry-desc">${escapeHtml(card.description)}</span>${status}</span>
<span class="entry-meta tabular"><span>${meta.map(escapeHtml).join(' · ')}</span><span>Updated ${formatDate(card.updated)}</span></span>
</a></li>`;
    }

    // Cheat sheets share one line. Each separator sits in the same no-wrap
    // span as the link before it, so a line never starts with a dot. Notes
    // for renamed or replaced tools follow the line, keyed to their link.
    function sheetsHtml(cards) {
        if (!cards.length) return '';
        const links = cards.map((c, i) =>
            `<span class="sheet"><a href="${escapeHtml(c.href)}" class="hub-card" ${hooks(c)}>${escapeHtml(c.title)}</a>${
                i < cards.length - 1 ? '<span class="sep hub-sep" aria-hidden="true"> · </span>' : ''}</span>`);
        const notes = cards.filter(c => c.status).map(c =>
            `<span class="sheet-note" data-note-for="${escapeHtml(c.href)}"><b>${escapeHtml(c.title)}:</b> ${escapeHtml(c.status)}</span>`);
        return `
<li class="sheets hub-sheets"><span class="sheets-label">Cheat sheets, one page each:</span> ${links.join(' ')}${
            notes.length ? `<span class="sheet-notes">${notes.join('')}</span>` : ''}</li>`;
    }

    function sectionHtml(cat, cards) {
        if (!cards.length) return '';
        const id = slugifyCategory(cat.name);
        const sorted = byRecency(cards).sort((a, b) => FORMAT_ORDER[a.format] - FORMAT_ORDER[b.format]);
        const full = sorted.filter(c => c.format !== 'reference');
        const sheets = sorted.filter(c => c.format === 'reference').sort((a, b) => a.title.localeCompare(b.title));
        return `
<section id="${id}" class="subject hub-section" aria-labelledby="${id}-h">
<div class="subject-head"><h2 id="${id}-h">${escapeHtml(cat.name)}</h2><span class="subject-count tabular hub-section-count" data-total="${cards.length}">${cards.length}</span></div>
<p class="subject-blurb">${escapeHtml(cat.blurb)}</p>
<ul class="entries">${full.map(rowHtml).join('')}${sheetsHtml(sheets)}
</ul>
</section>`;
    }

    // ------------------------------------------------------------------------
    // 4. Fragments
    //
    //    Every dynamic part of the page, as HTML strings keyed by element id.
    //    scripts/generate.mjs runs this file in Node and writes the fragments
    //    into index.html, so the catalogue is in the served HTML for search
    //    engines, link previews and readers without JavaScript. In the browser
    //    the same fragments are only injected if that pre-render is missing.
    // ------------------------------------------------------------------------

    function fragments() {
        const mins = CARDS.reduce((n, c) => n + (c.minutes || 0), 0);
        const dives = CARDS.filter(c => c.format === 'deep-dive').length;
        const recent = byRecency(CARDS.filter(c => c.updated)).slice(0, 3);
        const present = CATEGORIES.filter(cat => cardsIn(cat).length);
        return {
            'masthead-topics': present.map(cat =>
                `<a href="#${slugifyCategory(cat.name)}">${escapeHtml(cat.name)}</a>`).join(''),
            'library-stats': [`${CARDS.length} guides`, `${dives} deep dives`,
                `about ${Math.round(mins / 60)} hours of reading`].join(SEP),
            'format-key': FORMATS.map(f => `<span><b>${f.label}:</b> ${f.note}</span>`).join(''),
            'recent': `<h2>Recently updated</h2><ul>${recent.map(c =>
                `<li><a href="${escapeHtml(c.href)}">${escapeHtml(c.title)}</a>${SEP}${FORMAT_LABEL[c.format]}${SEP}<span class="tabular">${formatDate(c.updated, true)}</span></li>`).join('')}</ul>`,
            'format-buttons': [{ key: 'all', plural: 'All' }, ...FORMATS].map(f => {
                const n = f.key === 'all' ? CARDS.length : CARDS.filter(c => c.format === f.key).length;
                return `<button type="button" class="fmt-btn" data-format-filter="${f.key}" aria-pressed="${f.key === 'all'}">${f.plural} <span class="count tabular">${n}</span></button>`;
            }).join(''),
            'hub': CATEGORIES.map(cat => sectionHtml(cat, cardsIn(cat))).join(''),
        };
    }

    // Node (scripts/generate.mjs): hand over the fragments and stop.
    if (typeof document === 'undefined') {
        globalThis.__HUB_FRAGMENTS__ = fragments();
        return;
    }

    // ------------------------------------------------------------------------
    // 5. Filter: format buttons and search combine, and the state is kept in
    //    the address (?format=deep-dive&q=bond) so a filtered view can be
    //    shared or bookmarked.
    // ------------------------------------------------------------------------

    const VALID_FORMATS = new Set(['all', ...FORMATS.map(f => f.key)]);

    function setupFilter() {
        const input = document.getElementById('card-filter');
        const empty = document.getElementById('filter-empty');
        const status = document.getElementById('filter-status');
        const buttons = [...document.querySelectorAll('[data-format-filter]')];
        const params = new URLSearchParams(location.search);
        let format = VALID_FORMATS.has(params.get('format')) ? params.get('format') : 'all';
        if (input && params.get('q')) input.value = params.get('q');

        function syncUrl(q) {
            const p = new URLSearchParams(location.search);
            format === 'all' ? p.delete('format') : p.set('format', format);
            q ? p.set('q', q) : p.delete('q');
            const qs = p.toString();
            history.replaceState(null, '', location.pathname + (qs ? '?' + qs : '') + location.hash);
        }

        function apply() {
            const raw = input ? input.value.trim() : '';
            const q = raw.toLowerCase();
            const filtering = q || format !== 'all';
            let visibleTotal = 0;
            buttons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.formatFilter === format)));
            document.querySelectorAll('.hub-section').forEach(section => {
                let visible = 0;
                section.querySelectorAll('.hub-card').forEach(card => {
                    const match = (!q || card.dataset.search.includes(q)) && (format === 'all' || card.dataset.format === format);
                    card.hidden = !match;
                    if (match) visible++;
                });
                section.querySelectorAll('.hub-sheets').forEach(line => {
                    const links = [...line.querySelectorAll('.hub-card')];
                    line.hidden = links.every(a => a.hidden);
                    line.querySelectorAll('.hub-sep').forEach((sep, i) => {
                        sep.hidden = links[i].hidden || links.slice(i + 1).every(a => a.hidden);
                    });
                    line.querySelectorAll('[data-note-for]').forEach(note => {
                        const link = links.find(a => a.getAttribute('href') === note.dataset.noteFor);
                        note.hidden = !link || link.hidden;
                    });
                });
                const counter = section.querySelector('.hub-section-count');
                if (counter) counter.textContent = filtering ? `${visible} of ${counter.dataset.total}` : counter.dataset.total;
                section.hidden = visible === 0;
                visibleTotal += visible;
            });
            if (status) status.textContent = filtering ? `Showing ${visibleTotal} of ${CARDS.length}` : '';
            if (empty) empty.hidden = visibleTotal > 0;
            syncUrl(raw);
        }

        buttons.forEach(btn => btn.addEventListener('click', () => { format = btn.dataset.formatFilter; apply(); }));
        if (input) {
            input.addEventListener('input', apply);
            input.addEventListener('keydown', e => { if (e.key === 'Escape') { input.value = ''; apply(); } });
        }
        apply();
    }

    // ------------------------------------------------------------------------
    // 6. Bootstrap
    // ------------------------------------------------------------------------

    function init() {
        const root = document.getElementById('hub');
        // index.html ships pre-rendered; render only if that output is absent.
        if (root && !root.querySelector('.hub-section')) {
            const f = fragments();
            Object.keys(f).forEach(id => {
                const el = document.getElementById(id);
                if (el) el.innerHTML = f[id];
            });
        }
        setupFilter();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
